require 'simplecov'
SimpleCov.start do 
  add_filter "/spec/"
end


require 'rubygems'
require 'bundler/setup'

require 'beyonic'
require 'webmock/rspec'
require 'rspec/collection_matchers'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.expectation_framework = :rspec
  config.mock_framework = :rspec

  config.raise_errors_for_deprecations!
end

require 'webmock/rspec'
require 'vcr'

VCR.configure do |c|
  c.cassette_library_dir = 'fixtures/vcr_cassettes'
  c.ignore_hosts '127.0.0.1', 'localhost'
  c.hook_into :webmock
  c.before_record do |i|
    OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
  end
end
